#!/usr/bin/php
<?php
if(isset($argv[1]) && ($argv[1] == '-h' || $argv[1] == '--help')) {
	$string = 
///////////////////////////////////////////////////////////////{{{//
<<<HEREDOC
Descrition: Tools for create zone and get certificate for domains.
Usage: ./domain_handler

HEREDOC;
///////////////////////////////////////////////////////////////}}}//
	echo($string);
	exit(0);
}

require_once(__DIR__.'/../config.php');
require_once(__DIR__.'/../include/DB.php');
require_once(__DIR__.'/../include/db_init.php');
require_once(__DIR__.'/../include/DomainsHandler.php');

$DomainsHandler = new DomainsHandler();
$return = DomainsHandler::get_domains();
if(!is_array($return)) {//{{{//
	trigger_error("Can't get 'domains' for work", E_USER_ERROR);
	exit(255);
}//}}}//
$domains = $return;

$c = count($domains);
$n = 0;
foreach($domains as $array) {
	$n++;
	
	$domain = $array["domain"];
	$return = $DomainsHandler->set_domain($domain);
	if(!$return) continue;
	
	echo("{$n} of {$c} - {$domain}\n");

	$return = $DomainsHandler->delete_domain_data();
	if(!$return) {//{{{//
		trigger_error("Can't delete 'domain' data", E_USER_WARNING);
	}//}}}//

}

echo("Delete 'domains' data complete\n");
exit(0);

